theme: jekyll-theme-cayman
title: Torrent File Editor
w64_url: 
w32_url: https://github.com/torrent-file-editor/torrent-file-editor/releases/download/v0.3.15/torrent-file-editor-0.3.15-x32.exe
macos_url: https://github.com/torrent-file-editor/torrent-file-editor/releases/download/v0.3.15/torrent-file-editor-0.3.15.dmg
sources_url: https://github.com/torrent-file-editor/torrent-file-editor/releases/download/v0.3.15/torrent-file-editor-0.3.15.tar.gz
repository_url: https://github.com/torrent-file-editor/torrent-file-editor
langs:
  - {country: "sa", humanlang: "العربية - Arabic"}
  - {country: "bd", humanlang: "বাংলা - Bengali"}
  - {country: "cn", humanlang: "简体中文 - Chinese Simplified"}
  - {country: "tw", humanlang: "繁體中文 - Chinese Traditional"}
  - {country: "cz", humanlang: "Čeština - Czech"}
  - {country: "nl", humanlang: "Nederlands - Dutch"}
  - {country: "us", humanlang: "English - English"}
  - {country: "fi", humanlang: "Suomi - Finnish"}
  - {country: "fr", humanlang: "Français - French"}
  - {country: "de", humanlang: "Deutsch - German"}
  - {country: "il", humanlang: "עברית‎ - Hebrew"}
  - {country: "hu", humanlang: "Magyar - Hungarian"}
  - {country: "id", humanlang: "Indonesia - Indonesian"}
  - {country: "it", humanlang: "Italiano - Italian"}
  - {country: "jp", humanlang: "日本語 - Japanese"}
  - {country: "kr", humanlang: "한국어 - Korean"}
  - {country: "pl", humanlang: "Polski - Polish"}
  - {country: "br", humanlang: "Português  (Brasil) - Portuguese (Brazil)"}
  - {country: "ro", humanlang: "Română - Romanian"}
  - {country: "ru", humanlang: "Русский - Russian"}
  - {country: "es", humanlang: "Español - Spanish"}
  - {country: "tr", humanlang: "Türkçe - Turkish"}
  - {country: "vn", humanlang: "Tiếng Việt - Vietnamese"}

releases:
  - title: Windows x64
    icon: windows
    os: win64
  - title: Windows x32
    icon: windows
    os: win32
  - title: macOS
    icon: macos
    os: macos
  - title: Sources
    icon: linux
    os: linux

screenshots:
  - main
  - files
  - tree
  - raw
